export const MOCK_DATA = [
  {
    id: "7sN44O",
    fileName: "tperigoe0",
    uploadDate: "2023-04-28",
    fileType: "jpg",
    fileSize: "100 KB",
    printerID: "Q63IQY",
    fileStatus: "Chưa xác nhận",
  },
  {
    id: "5eNsnT",
    fileName: "ckelson1",
    uploadDate: "2023-04-26",
    fileType: "xlsx",
    fileSize: "50 KB",
    printerID: "52OJT6",
    fileStatus: "In xong",
  },
  {
    id: "3dGmxR",
    fileName: "jkasper2",
    uploadDate: "2023-04-30",
    fileType: "txt",
    fileSize: "500 KB",
    printerID: "2MUIBL",
    fileStatus: "In xong",
  },
  {
    id: "1vFUyG",
    fileName: "nbelvin3",
    uploadDate: "2022-12-27",
    fileType: "txt",
    fileSize: "1 KB",
    printerID: "771276",
    fileStatus: "Chưa xác nhận",
  },
  {
    id: "1jEtoC",
    fileName: "ghuggen4",
    uploadDate: "2023-02-07",
    fileType: "docx",
    fileSize: "50 KB",
    printerID: "2MUIBL",
    fileStatus: "In xong",
  },
  {
    id: "0aIciL",
    fileName: "sbugge5",
    uploadDate: "2023-11-01",
    fileType: "jpg",
    fileSize: "1 KB",
    printerID: "C355X2",
    fileStatus: "Đang in",
  },
  {
    id: "2iXD9U",
    fileName: "mfoxwell6",
    uploadDate: "2023-02-12",
    fileType: "pptx",
    fileSize: "5 KB",
    printerID: "T5Y815",
    fileStatus: "In xong",
  },
  {
    id: "5fH0bV",
    fileName: "jhavock7",
    uploadDate: "2023-07-24",
    fileType: "png",
    fileSize: "100 KB",
    printerID: "1YZ79K",
    fileStatus: "Đang in",
  },
  {
    id: "3nFkpW",
    fileName: "relsworth8",
    uploadDate: "2023-02-27",
    fileType: "txt",
    fileSize: "25 KB",
    printerID: "2XU4I0",
    fileStatus: "Đang in",
  },
  {
    id: "3zBIyI",
    fileName: "rverbeke9",
    uploadDate: "2023-06-09",
    fileType: "pptx",
    fileSize: "5 KB",
    printerID: "V8Q94I",
    fileStatus: "Đang in",
  },
  {
    id: "1nFsxT",
    fileName: "eillesa",
    uploadDate: "2023-02-10",
    fileType: "txt",
    fileSize: "2 KB",
    printerID: "FQPO73",
    fileStatus: "Chưa in",
  },
  {
    id: "2sYGwH",
    fileName: "bbebbingtonb",
    uploadDate: "2023-04-15",
    fileType: "pdf",
    fileSize: "25 KB",
    printerID: "4JQ8WC",
    fileStatus: "Đang in",
  },
  {
    id: "5zTam3",
    fileName: "gcartlidgec",
    uploadDate: "2023-06-04",
    fileType: "pptx",
    fileSize: "25 KB",
    printerID: "Q63IQY",
    fileStatus: "Chưa in",
  },
  {
    id: "1hNTfS",
    fileName: "caudibertd",
    uploadDate: "2023-04-28",
    fileType: "pdf",
    fileSize: "50 KB",
    printerID: "2MUIBL",
    fileStatus: "Chưa in",
  },
  {
    id: "2rZ2n2",
    fileName: "gbrazile",
    uploadDate: "2023-05-14",
    fileType: "xlsx",
    fileSize: "2 KB",
    printerID: "2MUIBL",
    fileStatus: "In xong",
  },
  {
    id: "0pYu5U",
    fileName: "cscoffinsf",
    uploadDate: "2023-10-03",
    fileType: "xlsx",
    fileSize: "200 KB",
    printerID: "ZLH6DR",
    fileStatus: "Chưa xác nhận",
  },
  {
    id: "3cEg73",
    fileName: "pregog",
    uploadDate: "2023-07-29",
    fileType: "png",
    fileSize: "10 KB",
    printerID: "P1JX36",
    fileStatus: "Đang in",
  },
  {
    id: "2dLpxW",
    fileName: "bpownallh",
    uploadDate: "2022-11-26",
    fileType: "pptx",
    fileSize: "200 KB",
    printerID: "771276",
    fileStatus: "Chưa in",
  },
  {
    id: "7lMNaV",
    fileName: "wpaxfordei",
    uploadDate: "2023-09-06",
    fileType: "png",
    fileSize: "2 KB",
    printerID: "C355X2",
    fileStatus: "In xong",
  },
  {
    id: "8hGd5F",
    fileName: "icracoej",
    uploadDate: "2023-04-24",
    fileType: "txt",
    fileSize: "25 KB",
    printerID: "FQPO73",
    fileStatus: "Chưa in",
  },
  {
    id: "7oKN7V",
    fileName: "djerredk",
    uploadDate: "2023-05-01",
    fileType: "jpg",
    fileSize: "10 KB",
    printerID: "D1K2XB",
    fileStatus: "Chưa xác nhận",
  },
  {
    id: "8cZ2iV",
    fileName: "ccasfordl",
    uploadDate: "2023-04-06",
    fileType: "pdf",
    fileSize: "5 KB",
    printerID: "Q63IQY",
    fileStatus: "Đang in",
  },
  {
    id: "7cMp2H",
    fileName: "cstocklem",
    uploadDate: "2023-08-18",
    fileType: "txt",
    fileSize: "100 KB",
    printerID: "0UC4E9",
    fileStatus: "Đang in",
  },
  {
    id: "0nQ0e2",
    fileName: "rkittlesn",
    uploadDate: "2023-07-17",
    fileType: "txt",
    fileSize: "10 KB",
    printerID: "M3IE7M",
    fileStatus: "Đang in",
  },
  {
    id: "3bACbQ",
    fileName: "bmackowleo",
    uploadDate: "2023-04-30",
    fileType: "docx",
    fileSize: "50 KB",
    printerID: "285009",
    fileStatus: "Đang in",
  },
  {
    id: "5kBZmR",
    fileName: "lneilusp",
    uploadDate: "2023-09-11",
    fileType: "png",
    fileSize: "100 KB",
    printerID: "F0DZO9",
    fileStatus: "Chưa xác nhận",
  },
  {
    id: "2gMd0G",
    fileName: "mkaubischq",
    uploadDate: "2023-10-19",
    fileType: "png",
    fileSize: "100 KB",
    printerID: "890N3D",
    fileStatus: "Đang in",
  },
  {
    id: "4vQfvI",
    fileName: "rbentingr",
    uploadDate: "2022-12-21",
    fileType: "docx",
    fileSize: "2 KB",
    printerID: "H11BN7",
    fileStatus: "Chưa xác nhận",
  },
  {
    id: "7bXweU",
    fileName: "vguesss",
    uploadDate: "2023-09-20",
    fileType: "jpg",
    fileSize: "1 KB",
    printerID: "X5G0T2",
    fileStatus: "Đang in",
  },
  {
    id: "7lUHvY",
    fileName: "pbramhamt",
    uploadDate: "2023-02-14",
    fileType: "docx",
    fileSize: "5 KB",
    printerID: "T5Y815",
    fileStatus: "Chưa xác nhận",
  },
  {
    id: "0zNxdM",
    fileName: "bgarretsonu",
    uploadDate: "2023-05-27",
    fileType: "png",
    fileSize: "10 KB",
    printerID: "7X216E",
    fileStatus: "Đang in",
  },
  {
    id: "0kLC5X",
    fileName: "sodeeganv",
    uploadDate: "2023-06-16",
    fileType: "jpg",
    fileSize: "100 KB",
    printerID: "890N3D",
    fileStatus: "Đang in",
  },
  {
    id: "2gRa6G",
    fileName: "tskottlew",
    uploadDate: "2023-01-23",
    fileType: "xlsx",
    fileSize: "200 KB",
    printerID: "H11BN7",
    fileStatus: "In xong",
  },
  {
    id: "4jR5iQ",
    fileName: "bmenilovex",
    uploadDate: "2023-02-22",
    fileType: "txt",
    fileSize: "25 KB",
    printerID: "KUPLE0",
    fileStatus: "In xong",
  },
  {
    id: "9mUV9A",
    fileName: "rstukingsy",
    uploadDate: "2022-12-31",
    fileType: "txt",
    fileSize: "10 KB",
    printerID: "2MUIBL",
    fileStatus: "Chưa xác nhận",
  },
  {
    id: "5jEUcA",
    fileName: "briddochz",
    uploadDate: "2023-02-10",
    fileType: "docx",
    fileSize: "1 KB",
    printerID: "3JAZ18",
    fileStatus: "In xong",
  },
  {
    id: "4lKO9L",
    fileName: "iworsham10",
    uploadDate: "2023-01-20",
    fileType: "jpg",
    fileSize: "25 KB",
    printerID: "92F67S",
    fileStatus: "Chưa xác nhận",
  },
  {
    id: "1kWmzG",
    fileName: "bcasson11",
    uploadDate: "2023-01-27",
    fileType: "pptx",
    fileSize: "25 KB",
    printerID: "B2U263",
    fileStatus: "Đang in",
  },
  {
    id: "6lBnf7",
    fileName: "dpedwell12",
    uploadDate: "2023-04-16",
    fileType: "pdf",
    fileSize: "10 KB",
    printerID: "M3IE7M",
    fileStatus: "Chưa xác nhận",
  },
  {
    id: "4mDK28",
    fileName: "bmacgahey13",
    uploadDate: "2023-07-28",
    fileType: "pptx",
    fileSize: "2 KB",
    printerID: "3E5A97",
    fileStatus: "Chưa in",
  },
  {
    id: "9xQevS",
    fileName: "biannitti14",
    uploadDate: "2022-12-02",
    fileType: "png",
    fileSize: "200 KB",
    printerID: "V09PA9",
    fileStatus: "In xong",
  },
  {
    id: "6xMCdM",
    fileName: "msharp15",
    uploadDate: "2023-04-11",
    fileType: "jpg",
    fileSize: "10 KB",
    printerID: "U7U898",
    fileStatus: "Đang in",
  },
  {
    id: "1nRFaA",
    fileName: "mcumberlidge16",
    uploadDate: "2023-04-21",
    fileType: "xlsx",
    fileSize: "2 KB",
    printerID: "O7EXY5",
    fileStatus: "In xong",
  },
  {
    id: "4oHnoL",
    fileName: "cmendus17",
    uploadDate: "2023-08-15",
    fileType: "jpg",
    fileSize: "2 KB",
    printerID: "39DXQ9",
    fileStatus: "Đang in",
  },
  {
    id: "6iMLbR",
    fileName: "mcovelle18",
    uploadDate: "2023-08-24",
    fileType: "docx",
    fileSize: "50 KB",
    printerID: "45PY10",
    fileStatus: "In xong",
  },
  {
    id: "9rWB6T",
    fileName: "pdeetlof19",
    uploadDate: "2023-01-09",
    fileType: "png",
    fileSize: "5 KB",
    printerID: "FQPO73",
    fileStatus: "Chưa xác nhận",
  },
  {
    id: "9gWgyM",
    fileName: "pgodwyn1a",
    uploadDate: "2023-06-27",
    fileType: "xlsx",
    fileSize: "100 KB",
    printerID: "T5Y815",
    fileStatus: "Chưa xác nhận",
  },
  {
    id: "7jGvi3",
    fileName: "gakister1b",
    uploadDate: "2023-05-26",
    fileType: "txt",
    fileSize: "200 KB",
    printerID: "3JAZ18",
    fileStatus: "Chưa in",
  },
  {
    id: "4bYFk9",
    fileName: "vleball1c",
    uploadDate: "2023-10-09",
    fileType: "pptx",
    fileSize: "50 KB",
    printerID: "2XU4I0",
    fileStatus: "Chưa xác nhận",
  },
  {
    id: "0tTJaE",
    fileName: "keldrett1d",
    uploadDate: "2023-01-09",
    fileType: "png",
    fileSize: "50 KB",
    printerID: "1OPZ46",
    fileStatus: "Chưa in",
  },
];
