export const MOCK_DATA = [
  {
    Code: "KUPLE0",
    printerName: "Xerox Phaser 6510",
    venue: 2,
    floor: 2,
    printerStatus: "Ít bận",
    building: "H2",
  },
  {
    Code: "U7U898",
    printerName: "Brother HL-L2380DW",
    venue: 2,
    floor: 5,
    printerStatus: "Đang bảo trì",
    building: "H6",
  },
  {
    Code: "B2U263",
    printerName: "Canon PIXMA MX922",
    venue: 2,
    floor: 7,
    printerStatus: "Ít bận",
    building: "H2",
  },
  {
    Code: "O7EXY5",
    printerName: "Canon PIXMA MX922",
    venue: 2,
    floor: 2,
    printerStatus: "Ít bận",
    building: "H6",
  },
  {
    Code: "YR42DQ",
    printerName: "Samsung Xpress C1860FW",
    venue: 2,
    floor: 8,
    printerStatus: "Bận",
    building: "H1",
  },
  {
    Code: "3J6BNE",
    printerName: "HP OfficeJet Pro 6978",
    venue: 1,
    floor: 2,
    printerStatus: "Bận",
    building: "A3",
  },
  {
    Code: "890N3D",
    printerName: "Xerox Phaser 6510",
    venue: 1,
    floor: 4,
    printerStatus: "Đang bảo trì",
    building: "A1",
  },
  {
    Code: "M3T5AO",
    printerName: "Xerox Phaser 6510",
    venue: 1,
    floor: 1,
    printerStatus: "Bận",
    building: "A3",
  },
  {
    Code: "FX91O3",
    printerName: "Samsung Xpress C1860FW",
    venue: 1,
    floor: 4,
    printerStatus: "Bận",
    building: "C2",
  },
  {
    Code: "ZLH6DR",
    printerName: "Canon PIXMA MX922",
    venue: 1,
    floor: 1,
    printerStatus: "Bận",
    building: "C6",
  },
  {
    Code: "2XU4I0",
    printerName: "HP OfficeJet Pro 6978",
    venue: 2,
    floor: 1,
    printerStatus: "Rảnh",
    building: "H6",
  },
  {
    Code: "FQPO73",
    printerName: "Brother HL-L2380DW",
    venue: 2,
    floor: 3,
    printerStatus: "Ít bận",
    building: "H6",
  },
  {
    Code: "45PY10",
    printerName: "Canon PIXMA MX922",
    venue: 2,
    floor: 2,
    printerStatus: "Ít bận",
    building: "H2",
  },
  {
    Code: "7YZ14F",
    printerName: "Samsung Xpress C1860FW",
    venue: 2,
    floor: 5,
    printerStatus: "Đang bảo trì",
    building: "H1",
  },
  {
    Code: "39DXQ9",
    printerName: "Samsung Xpress C1860FW",
    venue: 1,
    floor: 6,
    printerStatus: "Rảnh",
    building: "C5",
  },
  {
    Code: "45BOHO",
    printerName: "Canon PIXMA MX922",
    venue: 1,
    floor: 1,
    printerStatus: "Rảnh",
    building: "B5",
  },
  {
    Code: "92F67S",
    printerName: "Samsung Xpress C1860FW",
    venue: 2,
    floor: 5,
    printerStatus: "Bận",
    building: "H6",
  },
  {
    Code: "7X216E",
    printerName: "Samsung Xpress C1860FW",
    venue: 2,
    floor: 6,
    printerStatus: "Ít bận",
    building: "H1",
  },
  {
    Code: "9I66MS",
    printerName: "Xerox Phaser 6510",
    venue: 1,
    floor: 4,
    printerStatus: "Đang bảo trì",
    building: "B2",
  },
  {
    Code: "RNKC5R",
    printerName: "Brother HL-L2380DW",
    venue: 2,
    floor: 8,
    printerStatus: "Đang bảo trì",
    building: "H1",
  },
  {
    Code: "T5Y815",
    printerName: "Epson WorkForce WF-3640",
    venue: 1,
    floor: 7,
    printerStatus: "Đang bảo trì",
    building: "B1",
  },
  {
    Code: "4JQ8WC",
    printerName: "Canon PIXMA MX922",
    venue: 1,
    floor: 5,
    printerStatus: "Bận",
    building: "B3",
  },
  {
    Code: "2MUIBL",
    printerName: "Epson WorkForce WF-3640",
    venue: 1,
    floor: 6,
    printerStatus: "Đang bảo trì",
    building: "C3",
  },
  {
    Code: "0UC4E9",
    printerName: "HP OfficeJet Pro 6978",
    venue: 2,
    floor: 7,
    printerStatus: "Ít bận",
    building: "H2",
  },
  {
    Code: "Q63IQY",
    printerName: "Brother HL-L2380DW",
    venue: 1,
    floor: 1,
    printerStatus: "Bận",
    building: "A3",
  },
  {
    Code: "N41ZC1",
    printerName: "Brother HL-L2380DW",
    venue: 1,
    floor: 5,
    printerStatus: "Đang bảo trì",
    building: "A5",
  },
  {
    Code: "3JAZ18",
    printerName: "Xerox Phaser 6510",
    venue: 1,
    floor: 1,
    printerStatus: "Đang bảo trì",
    building: "A2",
  },
  {
    Code: "H11BN7",
    printerName: "Samsung Xpress C1860FW",
    venue: 1,
    floor: 1,
    printerStatus: "Rảnh",
    building: "C2",
  },
  {
    Code: "X5G0T2",
    printerName: "Xerox Phaser 6510",
    venue: 1,
    floor: 5,
    printerStatus: "Ít bận",
    building: "C1",
  },
  {
    Code: "1OPZ46",
    printerName: "Canon PIXMA MX922",
    venue: 2,
    floor: 8,
    printerStatus: "Rảnh",
    building: "H2",
  },
  {
    Code: "4U478G",
    printerName: "Canon PIXMA MX922",
    venue: 2,
    floor: 3,
    printerStatus: "Rảnh",
    building: "H6",
  },
  {
    Code: "D1K2XB",
    printerName: "Xerox Phaser 6510",
    venue: 2,
    floor: 1,
    printerStatus: "Bận",
    building: "H6",
  },
  {
    Code: "7CZVC9",
    printerName: "Canon PIXMA MX922",
    venue: 1,
    floor: 6,
    printerStatus: "Rảnh",
    building: "B7",
  },
  {
    Code: "52OJT6",
    printerName: "Brother HL-L2380DW",
    venue: 2,
    floor: 7,
    printerStatus: "Bận",
    building: "H2",
  },
  {
    Code: "V8Q94I",
    printerName: "Samsung Xpress C1860FW",
    venue: 2,
    floor: 8,
    printerStatus: "Rảnh",
    building: "H6",
  },
  {
    Code: "285009",
    printerName: "Xerox Phaser 6510",
    venue: 2,
    floor: 2,
    printerStatus: "Đang bảo trì",
    building: "H3",
  },
  {
    Code: "72AJRR",
    printerName: "Epson WorkForce WF-3640",
    venue: 1,
    floor: 2,
    printerStatus: "Ít bận",
    building: "B8",
  },
  {
    Code: "3E5A97",
    printerName: "Samsung Xpress C1860FW",
    venue: 1,
    floor: 7,
    printerStatus: "Đang bảo trì",
    building: "A1",
  },
  {
    Code: "85D68J",
    printerName: "Brother HL-L2380DW",
    venue: 2,
    floor: 3,
    printerStatus: "Ít bận",
    building: "H1",
  },
  {
    Code: "M3IE7M",
    printerName: "Samsung Xpress C1860FW",
    venue: 1,
    floor: 7,
    printerStatus: "Đang bảo trì",
    building: "B3",
  },
  {
    Code: "MKJ05W",
    printerName: "Samsung Xpress C1860FW",
    venue: 2,
    floor: 4,
    printerStatus: "Đang bảo trì",
    building: "H3",
  },
  {
    Code: "C355X2",
    printerName: "Epson WorkForce WF-3640",
    venue: 2,
    floor: 3,
    printerStatus: "Bận",
    building: "H2",
  },
  {
    Code: "D83FPC",
    printerName: "HP OfficeJet Pro 6978",
    venue: 1,
    floor: 1,
    printerStatus: "Rảnh",
    building: "C6",
  },
  {
    Code: "014551",
    printerName: "Epson WorkForce WF-3640",
    venue: 2,
    floor: 3,
    printerStatus: "Đang bảo trì",
    building: "H2",
  },
  {
    Code: "F0DZO9",
    printerName: "HP OfficeJet Pro 6978",
    venue: 2,
    floor: 6,
    printerStatus: "Bận",
    building: "H1",
  },
  {
    Code: "771276",
    printerName: "Epson WorkForce WF-3640",
    venue: 1,
    floor: 3,
    printerStatus: "Đang bảo trì",
    building: "C6",
  },
  {
    Code: "1YZ79K",
    printerName: "Xerox Phaser 6510",
    venue: 1,
    floor: 4,
    printerStatus: "Bận",
    building: "C5",
  },
  {
    Code: "V09PA9",
    printerName: "Xerox Phaser 6510",
    venue: 1,
    floor: 6,
    printerStatus: "Bận",
    building: "B1",
  },
  {
    Code: "92ICHG",
    printerName: "HP OfficeJet Pro 6978",
    venue: 1,
    floor: 6,
    printerStatus: "Rảnh",
    building: "B2",
  },
  {
    Code: "P1JX36",
    printerName: "Samsung Xpress C1860FW",
    venue: 1,
    floor: 1,
    printerStatus: "Ít bận",
    building: "A4",
  },
];
