export const MOCK_DATA = [
  {
    ID: "KUPLE0",
    printerName: "Xerox Phaser 6510",
    venue: 2,
    floor: 2,
    printerStatus: "Ít bận",
    building: "H2",
  },
  {
    ID: "U7U898",
    printerName: "Brother HL-L2380DW",
    venue: 2,
    floor: 5,
    printerStatus: "Đang bảo trì",
    building: "H6",
  },
  {
    ID: "B2U263",
    printerName: "Canon PIXMA MX922",
    venue: 2,
    floor: 7,
    printerStatus: "Ít bận",
    building: "H2",
  },
  {
    ID: "O7EXY5",
    printerName: "Canon PIXMA MX922",
    venue: 2,
    floor: 2,
    printerStatus: "Ít bận",
    building: "H6",
  },
  {
    ID: "YR42DQ",
    printerName: "Samsung Xpress C1860FW",
    venue: 2,
    floor: 8,
    printerStatus: "Bận",
    building: "H1",
  },
  {
    ID: "3J6BNE",
    printerName: "HP OfficeJet Pro 6978",
    venue: 1,
    floor: 2,
    printerStatus: "Bận",
    building: "H3",
  },
  {
    ID: "890N3D",
    printerName: "Xerox Phaser 6510",
    venue: 1,
    floor: 4,
    printerStatus: "Đang bảo trì",
    building: "H6",
  },
  {
    ID: "M3T5AO",
    printerName: "Xerox Phaser 6510",
    venue: 1,
    floor: 1,
    printerStatus: "Bận",
    building: "H2",
  },
  {
    ID: "FX91O3",
    printerName: "Samsung Xpress C1860FW",
    venue: 1,
    floor: 4,
    printerStatus: "Bận",
    building: "H2",
  },
  {
    ID: "ZLH6DR",
    printerName: "Canon PIXMA MX922",
    venue: 1,
    floor: 1,
    printerStatus: "Bận",
    building: "H3",
  },
  {
    ID: "2XU4I0",
    printerName: "HP OfficeJet Pro 6978",
    venue: 2,
    floor: 1,
    printerStatus: "Rảnh",
    building: "H6",
  },
  {
    ID: "FQPO73",
    printerName: "Brother HL-L2380DW",
    venue: 2,
    floor: 3,
    printerStatus: "Ít bận",
    building: "H6",
  },
  {
    ID: "45PY10",
    printerName: "Canon PIXMA MX922",
    venue: 2,
    floor: 2,
    printerStatus: "Ít bận",
    building: "H2",
  },
  {
    ID: "7YZ14F",
    printerName: "Samsung Xpress C1860FW",
    venue: 2,
    floor: 5,
    printerStatus: "Đang bảo trì",
    building: "H1",
  },
  {
    ID: "39DXQ9",
    printerName: "Samsung Xpress C1860FW",
    venue: 1,
    floor: 6,
    printerStatus: "Rảnh",
    building: "H1",
  },
  {
    ID: "45BOHO",
    printerName: "Canon PIXMA MX922",
    venue: 1,
    floor: 1,
    printerStatus: "Rảnh",
    building: "H2",
  },
  {
    ID: "92F67S",
    printerName: "Samsung Xpress C1860FW",
    venue: 2,
    floor: 5,
    printerStatus: "Bận",
    building: "H6",
  },
  {
    ID: "7X216E",
    printerName: "Samsung Xpress C1860FW",
    venue: 2,
    floor: 6,
    printerStatus: "Ít bận",
    building: "H1",
  },
  {
    ID: "9I66MS",
    printerName: "Xerox Phaser 6510",
    venue: 1,
    floor: 4,
    printerStatus: "Đang bảo trì",
    building: "H2",
  },
  {
    ID: "RNKC5R",
    printerName: "Brother HL-L2380DW",
    venue: 2,
    floor: 8,
    printerStatus: "Đang bảo trì",
    building: "H1",
  },
  {
    ID: "T5Y815",
    printerName: "Epson WorkForce WF-3640",
    venue: 1,
    floor: 7,
    printerStatus: "Đang bảo trì",
    building: "H1",
  },
  {
    ID: "4JQ8WC",
    printerName: "Canon PIXMA MX922",
    venue: 1,
    floor: 5,
    printerStatus: "Bận",
    building: "H3",
  },
  {
    ID: "2MUIBL",
    printerName: "Epson WorkForce WF-3640",
    venue: 1,
    floor: 6,
    printerStatus: "Đang bảo trì",
    building: "H2",
  },
  {
    ID: "0UC4E9",
    printerName: "HP OfficeJet Pro 6978",
    venue: 2,
    floor: 7,
    printerStatus: "Ít bận",
    building: "H2",
  },
  {
    ID: "Q63IQY",
    printerName: "Brother HL-L2380DW",
    venue: 1,
    floor: 1,
    printerStatus: "Bận",
    building: "H3",
  },
  {
    ID: "N41ZC1",
    printerName: "Brother HL-L2380DW",
    venue: 1,
    floor: 5,
    printerStatus: "Đang bảo trì",
    building: "H2",
  },
  {
    ID: "3JAZ18",
    printerName: "Xerox Phaser 6510",
    venue: 1,
    floor: 1,
    printerStatus: "Đang bảo trì",
    building: "H2",
  },
  {
    ID: "H11BN7",
    printerName: "Samsung Xpress C1860FW",
    venue: 1,
    floor: 1,
    printerStatus: "Rảnh",
    building: "H2",
  },
  {
    ID: "X5G0T2",
    printerName: "Xerox Phaser 6510",
    venue: 1,
    floor: 5,
    printerStatus: "Ít bận",
    building: "H1",
  },
  {
    ID: "1OPZ46",
    printerName: "Canon PIXMA MX922",
    venue: 2,
    floor: 8,
    printerStatus: "Rảnh",
    building: "H2",
  },
  {
    ID: "4U478G",
    printerName: "Canon PIXMA MX922",
    venue: 2,
    floor: 3,
    printerStatus: "Rảnh",
    building: "H6",
  },
  {
    ID: "D1K2XB",
    printerName: "Xerox Phaser 6510",
    venue: 2,
    floor: 1,
    printerStatus: "Bận",
    building: "H6",
  },
  {
    ID: "7CZVC9",
    printerName: "Canon PIXMA MX922",
    venue: 1,
    floor: 6,
    printerStatus: "Rảnh",
    building: "H2",
  },
  {
    ID: "52OJT6",
    printerName: "Brother HL-L2380DW",
    venue: 2,
    floor: 7,
    printerStatus: "Bận",
    building: "H2",
  },
  {
    ID: "V8Q94I",
    printerName: "Samsung Xpress C1860FW",
    venue: 2,
    floor: 8,
    printerStatus: "Rảnh",
    building: "H6",
  },
  {
    ID: "285009",
    printerName: "Xerox Phaser 6510",
    venue: 2,
    floor: 2,
    printerStatus: "Đang bảo trì",
    building: "H3",
  },
  {
    ID: "72AJRR",
    printerName: "Epson WorkForce WF-3640",
    venue: 1,
    floor: 2,
    printerStatus: "Ít bận",
    building: "H3",
  },
  {
    ID: "3E5A97",
    printerName: "Samsung Xpress C1860FW",
    venue: 1,
    floor: 7,
    printerStatus: "Đang bảo trì",
    building: "H2",
  },
  {
    ID: "85D68J",
    printerName: "Brother HL-L2380DW",
    venue: 2,
    floor: 3,
    printerStatus: "Ít bận",
    building: "H1",
  },
  {
    ID: "M3IE7M",
    printerName: "Samsung Xpress C1860FW",
    venue: 1,
    floor: 7,
    printerStatus: "Đang bảo trì",
    building: "H6",
  },
  {
    ID: "MKJ05W",
    printerName: "Samsung Xpress C1860FW",
    venue: 2,
    floor: 4,
    printerStatus: "Đang bảo trì",
    building: "H3",
  },
  {
    ID: "C355X2",
    printerName: "Epson WorkForce WF-3640",
    venue: 2,
    floor: 3,
    printerStatus: "Bận",
    building: "H2",
  },
  {
    ID: "D83FPC",
    printerName: "HP OfficeJet Pro 6978",
    venue: 1,
    floor: 1,
    printerStatus: "Rảnh",
    building: "H1",
  },
  {
    ID: "014551",
    printerName: "Epson WorkForce WF-3640",
    venue: 2,
    floor: 3,
    printerStatus: "Đang bảo trì",
    building: "H2",
  },
  {
    ID: "F0DZO9",
    printerName: "HP OfficeJet Pro 6978",
    venue: 2,
    floor: 6,
    printerStatus: "Bận",
    building: "H1",
  },
  {
    ID: "771276",
    printerName: "Epson WorkForce WF-3640",
    venue: 2,
    floor: 3,
    printerStatus: "Đang bảo trì",
    building: "H2",
  },
  {
    ID: "1YZ79K",
    printerName: "Xerox Phaser 6510",
    venue: 1,
    floor: 4,
    printerStatus: "Bận",
    building: "H1",
  },
  {
    ID: "V09PA9",
    printerName: "Xerox Phaser 6510",
    venue: 2,
    floor: 6,
    printerStatus: "Bận",
    building: "H6",
  },
  {
    ID: "92ICHG",
    printerName: "HP OfficeJet Pro 6978",
    venue: 1,
    floor: 6,
    printerStatus: "Rảnh",
    building: "H1",
  },
  {
    ID: "P1JX36",
    printerName: "Samsung Xpress C1860FW",
    venue: 1,
    floor: 1,
    printerStatus: "Ít bận",
    building: "H1",
  },
];
